[package]
name = "libzfs"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
libc = "0.2.140"

[dependencies.libzfs-sys]
path = "libzfs-sys"

[dependencies.os_pipe]
version = "1.1.3"
features = ["io_safety"]
