[package]
name = "libzfs"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>"]

[dependencies.libzfs-sys]
path = "libzfs-sys"

[profile.release]
lto = true

[workspace]
members = [".", "libzfs-sys"]
